openapi: 3.0.4

info:
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Production
    url: "https://api.algashop.com"

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        201:
          description: Customer Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
          headers:
            Location:
              schema:
                type: string
                example: "/api/v1/customers/019c7b95-f43f-7b27-95a3-4f609adecca9"
              description: Get Customer Created
        400:
          $ref: "#/components/responses/BadRequest"
        409:
          $ref: "#/components/responses/Conflict"
        422:
          $ref: "#/components/responses/UnprocessableEntity"
        500:
          $ref: "#/components/responses/InternalError"
    get:
      description: List customers
      tags:
        - Customers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Page"
                  - type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/Customer"

  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: List single customer by id
      tags:
        - Customers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          $ref: "#/components/responses/NotFound"

    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: Edit customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerUpdateInput"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          $ref: "#/components/responses/NotFound"
        400:
          $ref: "#/components/responses/BadRequest"
        409:
          $ref: "#/components/responses/Conflict"
        422:
          $ref: "#/components/responses/UnprocessableEntity"
        500:
          $ref: "#/components/responses/InternalError"

    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: Delete customer
      tags:
        - Customers
      responses:
        204:
          description: No Content
        404:
          $ref: "#/components/responses/NotFound"

components:
  responses:
    NotFound:
      description: Resource not Found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    BadRequest:
      description: Invalid request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    InternalError:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    Conflict:
      description: Conflict resource
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"
    UnprocessableEntity:
      description: Unprocessable entity
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetail"

  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - document
        - phone
        - loyaltyPoints
        - archived
        - archivedAt
        - registeredAt
        - promotionNotificationsAllowed
        - birthDate
        - address
      properties:
        id:
          type: string
          example: "019c7b9a-afab-776e-a20f-451ab1b3b06d"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "john.doe@email.com"
        document:
          type: string
          example: "1234"
        phone:
          type: string
          example: "412412"
        birthDate:
          type: string
          format: date
          example: "1990-03-21"
        loyaltyPoints:
          type: number
          example: 10
        registeredAt:
          type: string
          format: date-time
          example: "2024-04-02T00:12:45Z"
        archivedAt:
          type: string
          format: date-time
          example: "2024-04-06T00:12:45Z"
        promotionNotificationsAllowed:
          type: boolean
          example: true
        archived:
          type: boolean
          example: false
        address:
          $ref: "#/components/schemas/Address"

    Address:
      type: object
      required:
        - street
        - number
        - complement
        - neighborhood
        - city
        - state
        - zipCode
      properties:
        street:
          type: string
          example: "Bourbon Street"
          x-validation: "notBlank"
          nullable: false
        number:
          type: string
          example: "123"
          x-validation: "notBlank"
          nullable: false
        complement:
          type: string
          example: "apt 122"
          x-validation: "notBlank"
          nullable: false
        neighborhood:
          type: string
          example: "North Vile"
          x-validation: "notBlank"
          nullable: false
        city:
          type: string
          example: "Yorstfort"
          x-validation: "notBlank"
          nullable: false
        state:
          type: string
          example: "South Carolina"
          x-validation: "notBlank"
          nullable: false
        zipCode:
          type: string
          example: "1235"
          x-validation: "notBlank"
          nullable: false

    CustomerInput:
      type: object
      required:
        - firstName
        - lastName
        - email
        - document
        - phone
        - promotionNotificationsAllowed
        - birthDate
        - address
      properties:
        firstName:
          type: string
          example: "John"
          x-validation: "notBlank"
          nullable: false
        lastName:
          type: string
          example: "Doe"
          x-validation: "notBlank"
          nullable: false
        email:
          type: string
          example: "john.doe@email.com"
          x-validation: "email"
          nullable: false
        document:
          type: string
          example: "1234"
          x-validation: "notBlank"
          nullable: false
        phone:
          type: string
          example: "412412"
          x-validation: "notBlank"
          nullable: false
        promotionNotificationsAllowed:
          type: boolean
          example: true
          nullable: false
        birthDate:
          type: string
          format: date
          example: "1990-03-21"
          x-validation: "pastDate"
          nullable: false
        address:
          $ref: "#/components/schemas/Address"

    CustomerUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "412412"
          nullable: false
          x-validation: "notBlank"
        promotionNotificationsAllowed:
          type: boolean
          example: true
          nullable: false
        address:
          $ref: "#/components/schemas/Address"

    ProblemDetail:
      type: object
      required:
        - status
        - type
      properties:
        status:
          type: integer
          example: 400
        type:
          type: string
          example: "/errors/invalid-data"
        title:
          type: string
          example: Invalid Fields
        instance:
          type: string
          example: "/api/v1/customers"
        detail:
          type: string
          example: One or more fields are invalid
        fields:
          type: object
          description: Fields that cause the error

    Page:
      type: object
      required:
        - number
        - size
        - totalPages
        - totalElements
        - content
      properties:
        number:
          type: integer
          example: 2
        size:
          type: integer
          example: 9
        totalPages:
          type: integer
          example: 15
        totalElements:
          type: integer
          example: 150
