openapi: 3.0.4

info:
  title: AlgaShop - Ordering
  version: "1.0"

servers:
  - description: Development
    url: "http://localhost:8080"
  - description: Production
    url: "https://api.algashop.com"

paths:
  /api/v1/customers:
    post:
      description: Register a new customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerInput"
      responses:
        201:
          description: Customer Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
          headers:
            Location:
              schema:
                type: string
                example: "/api/v1/customers/019c7b95-f43f-7b27-95a3-4f609adecca9"
              description: Get Customer Created
        400:
          description: Bad Request
        409:
          description: Conflict
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error
    get:
      description: List customers
      tags:
        - Customers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customer"

  /api/v1/customers/{customerId}:
    get:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: List single customer by id
      tags:
        - Customers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          description: Not Found

    put:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: Edit customer
      tags:
        - Customers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerUpdateInput"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Customer"
        404:
          description: Not Found
        400:
          description: Bad Request
        409:
          description: Conflict
        422:
          description: Unprocessable Entity
        500:
          description: Internal Server Error

    delete:
      parameters:
        - schema:
            type: string
          name: customerId
          in: path
          required: true
          example: "019c7b95-f43f-7b27-95a3-4f609adecca9"
      description: Delete customer
      tags:
        - Customers
      responses:
        204:
          description: No Content
        404:
          description: Not Found

components:
  schemas:
    Customer:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
        - document
        - phone
        - loyaltyPoints
        - archived
        - archivedAt
        - registeredAt
        - promotionNotificationsAllowed
        - birthDate
        - address
      properties:
        id:
          type: string
          example: "019c7b9a-afab-776e-a20f-451ab1b3b06d"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        email:
          type: string
          example: "john.doe@email.com"
        document:
          type: string
          example: "1234"
        phone:
          type: string
          example: "412412"
        birthDate:
          type: string
          format: date
          example: "1990-03-21"
        loyaltyPoints:
          type: number
          example: 10
        registeredAt:
          type: string
          format: date-time
          example: "2024-04-02T00:12:45Z"
        archivedAt:
          type: string
          format: date-time
          example: "2024-04-06T00:12:45Z"
        promotionNotificationsAllowed:
          type: boolean
          example: true
        archived:
          type: boolean
          example: false
        address:
          $ref: "#/components/schemas/Address"

    Address:
      type: object
      required:
        - street
        - number
        - complement
        - neighborhood
        - city
        - state
        - zipCode
      properties:
        street:
          type: string
          example: "Bourbon Street"
          x-validation: "notBlank"
          nullable: false
        number:
          type: string
          example: "123"
          x-validation: "notBlank"
          nullable: false
        complement:
          type: string
          example: "apt 122"
          x-validation: "notBlank"
          nullable: false
        neighborhood:
          type: string
          example: "North Vile"
          x-validation: "notBlank"
          nullable: false
        city:
          type: string
          example: "Yorstfort"
          x-validation: "notBlank"
          nullable: false
        state:
          type: string
          example: "South Carolina"
          x-validation: "notBlank"
          nullable: false
        zipCode:
          type: string
          example: "1235"
          x-validation: "notBlank"
          nullable: false

    CustomerInput:
      type: object
      required:
        - firstName
        - lastName
        - email
        - document
        - phone
        - promotionNotificationsAllowed
        - birthDate
        - address
      properties:
        firstName:
          type: string
          example: "John"
          x-validation: "notBlank"
          nullable: false
        lastName:
          type: string
          example: "Doe"
          x-validation: "notBlank"
          nullable: false
        email:
          type: string
          example: "john.doe@email.com"
          x-validation: "email"
          nullable: false
        document:
          type: string
          example: "1234"
          x-validation: "notBlank"
          nullable: false
        phone:
          type: string
          example: "412412"
          x-validation: "notBlank"
          nullable: false
        promotionNotificationsAllowed:
          type: boolean
          example: true
          nullable: false
        birthDate:
          type: string
          format: date
          example: "1990-03-21"
          x-validation: "pastDate"
          nullable: false
        address:
          $ref: "#/components/schemas/Address"

    CustomerUpdateInput:
      type: object
      required:
        - firstName
        - lastName
        - phone
        - promotionNotificationsAllowed
        - address
      properties:
        firstName:
          type: string
          example: "John"
          nullable: false
          x-validation: "notBlank"
        lastName:
          type: string
          example: "Doe"
          nullable: false
          x-validation: "notBlank"
        phone:
          type: string
          example: "412412"
          nullable: false
          x-validation: "notBlank"
        promotionNotificationsAllowed:
          type: boolean
          example: true
          nullable: false
        address:
          $ref: "#/components/schemas/Address"
